repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black # use pyproject.toml to config
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8  # use .flake8 file to config