repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black # use pyproject.toml to config
-   repo: https://github.com/pycqa/flake8
    rev: stable
    hooks:
    - id: flake8  # use .flake8 file to config.