name: Publish PyEuropeana to PyPI 

on: push
    branches:
      - stable

jobs:
  build-and-publish:
    name: Build and publish PyEuropeana to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # make pull request repo available inside the vm
      - name: Set up Python 3.9
       uses: actions/setup-python@v3 # vm already has python, but I want a specific version
        with:
          python-version: '^3.7'

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@v3
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          repository_url: https://pypi.org
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v3
        with:
          password: ${{ secrets.PYPI_TOKEN }}