name: stylecheck
on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
      - 'tests/**'
jobs:
  flake8-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # make pull request repo available inside the vm
      - uses: actions/setup-python@v3 # vm already has python, but I want a specific version
        with:
          python-version: '^3.7'
      - run: python -m pip install flake8
      - run: flake8 src --max-line-length=88 --max-complexity=18 --ignore=E203,E266,E501,W503,F403,F401,W605
      - run: flake8 tests --max-line-length=88 --max-complexity=18 --ignore=E203,E266,E501,W503,F403,F401,W605
